export const ActionTypes = {
    SET_SPORTSMANS: "SET_SPORTSMANS",
    SELECTED_SPORTSMAN: "SELECTED_SPORTSMAN",
    ADD_SPORTSMAN: "ADD_SPORTSMAN",
    DELETE_SPORTSMAN: "DELETE_SPORTSMAN",
    SET_COMPETITIONS: 'SET_COMPETITIONS',
    ADD_COMPETITION: 'ADD_COMPETITION',
    DELETE_COMPETITION: 'DELETE_COMPETITION',
    SET_REGULATIONS: 'SET_REGULATIONS',
    ADD_REGULATION: 'ADD_REGULATION',
    DELETE_REGULATION: 'DELETE_REGULATION',
};